language: cpp
compiler:
  - clang

git:
  depth: 1

before_install:
  - sudo apt-get -qq update
  - sudo apt-get -qq install git clang cmake make gcc g++ libmariadbclient-dev libssl-dev libbz2-dev libreadline-dev libncurses-dev libboost-all-dev mariadb-server p7zip libmariadb-client-lgpl-dev-compat
  - export CC=clang-3.5 CXX=clang++-3.5

install:
  - mkdir bin
  - cd bin
  - cmake ../ -DWITH_WARNINGS=1 -DWITH_COREDEBUG=0 -DUSE_COREPCH=1 -DUSE_SCRIPTPCH=1 -DTOOLS=1 -DSCRIPTS=1 -DSERVERS=1 -DNOJEM=1 -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_FLAGS="-Werror" -DCMAKE_CXX_FLAGS="-Werror"
  - cd ..
  - sudo chmod +x contrib/check_updates.sh

script:
  - $CXX --version
  - mysql -uroot < sql/create/create_mysql.sql
  - mysql -utrinity -ptrinity auth < sql/base/auth_database.sql
  - ./contrib/check_updates.sh auth auth
  - mysql -utrinity -ptrinity characters < sql/base/characters_database.sql
  - ./contrib/check_updates.sh characters characters
  - mysql -utrinity -ptrinity world < sql/base/dev/world_database.sql
  - mysql -utrinity -ptrinity hotfixes < sql/base/dev/hotfixes_database.sql
  - cat sql/updates/world/*.sql | mysql -utrinity -ptrinity world
  - cat sql/updates/hotfixes/*.sql | mysql -utrinity -ptrinity hotfixes
  - mysql -uroot < sql/create/drop_mysql.sql
  - cd bin
  - make -j 8 -k
